Add Entity.Item and OnEntityMetadata event
ORelio/Minecraft-Console-Client pull request #1222
Opened 2020-08-18 21:58 UTC by Nekiplay

2020-08-19 06:17 UTC, Nekiplay commented
![image](https://user-images.githubusercontent.com/35975332/90598960-71356b80-e20d-11ea-90f8-b90de78cbb87.png)
Strangely, for some reason it gives an error on the iron ingot.

2020-08-19 10:31 UTC, Nekiplay reviewed
Done

2020-08-20 10:45 UTC, ORelio requested changes
Thanks for your contribution! There are some things that would need to be addressed before merging:

2020-08-20 10:45 UTC, ORelio commented on MinecraftClient/ChatBot.cs
> +        public virtual void OnDeath() { }
I think this event is already present as per #1220. Could you remove it from the PR?

2020-08-20 10:45 UTC, ORelio commented on MinecraftClient/ChatBot.cs
> +        public virtual void OnEntityMetadata(int entityID, Dictionary<int, object> metadata) { }
Should be `OnEntityMetadata(Entity entity [...]` for consistency with other APIs

2020-08-20 10:45 UTC, ORelio commented on MinecraftClient/ChatBot.cs
> +        public virtual void OnEntityHealth(Entity entity, float health) { }
Good idea 👍

2020-08-20 10:45 UTC, ORelio commented on MinecraftClient/Mapping/EntityPose.cs
> +        Fall_Flying = 1,
Case should be `FallFlying` (same for `SpinAttack` below)

2020-08-20 10:45 UTC, ORelio commented on MinecraftClient/McClient.cs
> +                DispatchBotEvent(bot => bot.OnDeath());
Already present since #1220, should be removed from this PR

2020-08-20 10:45 UTC, ORelio commented on MinecraftClient/McClient.cs
> +                Dictionary<int, Entity> keyValuePairs = GetEntities();
(1/2) No need to call `GetEntities()` here, you can access `entities` directly since it's an internal field

2020-08-20 10:45 UTC, ORelio commented on MinecraftClient/McClient.cs
> +                foreach (KeyValuePair<int, Entity> ent in keyValuePairs)
(2/2)... so here the loop becomes `foreach (KeyValuePair<int, Entity> ent in entities)`

2020-08-20 10:45 UTC, ORelio commented on MinecraftClient/McClient.cs
> +                    int healthField = protocolversion >= 477 ? 8 : 7; // Health is field no. 7 in 1.10+ and 8 in 1.14+
As discussed in #1205 the protocol handler should handle this, protocol versions should not be necessary in McClient.cs, hence the OnEntityHealth() event. ChatBots will likely not be able to exploit the event due to fields being different between versions: the `Dictionary<int, object> metadata` is dependant on protocol versions so it might not be very helpful as is. The only things I can think of to maintiain an `OnEntityMetadata` would be to make an `EntityMetadata` class with fields that will never change between versions and populate it from the protocol handler, or pass an Entity field with metadata already set by the protocol handler 🤔

2020-08-20 16:35 UTC, ORelio approved these changes
Manually fixed unadressed issues.

2020-08-20 16:36 UTC, merged