Add support German language support
ORelio/Minecraft-Console-Client pull request #1526
Opened 2021-04-05 16:12 UTC by Daenges

Had some time and tried my best to translate everything.

2021-04-06 17:11 UTC, ORelio commented
Looks good... but I can't read German! Is there anyone out there who could help proofreading? 😄
Otherwise don't worry @Daenges I'll merge after a few days, the translation file itself looks correctly formatted 😉

2021-04-06 17:56 UTC, Daenges commented
Just a small question: Does line 372 refere to a crafting table or a table where the recipes are stored? @ORelio

2021-04-06 21:09 UTC, ORelio commented
Well, `tablelocation` is an AutoCraft setting for specifying the location of the crafting table. It is the name of the field in config file so it should be kept as is in your error message.

https://github.com/ORelio/Minecraft-Console-Client/blob/f20abb6fbc59b4781e6ff0a80b077f471ecab6b1/MinecraftClient/ChatBots/AutoCraft.cs#L283

https://github.com/ORelio/Minecraft-Console-Client/blob/f20abb6fbc59b4781e6ff0a80b077f471ecab6b1/MinecraftClient/ChatBots/AutoCraft.cs#L370-L378

https://github.com/ORelio/Minecraft-Console-Client/blob/53e24132040546d7655084c76473e0bc54ed731c/MinecraftClient/Resources/lang/en.ini#L372

2021-04-07 08:54 UTC, cyb3rko requested changes

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +debug.crypto=§8Crypto keys & hash wurden generiert.
```suggestion
debug.crypto=§8Crypto-Schlüssel & -Hash wurden generiert.
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +mcc.session=Überprüfe Session...
```suggestion
mcc.session=Überprüfe Sitzung...
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +mcc.session=Überprüfe Session...
Fixing inconsistent translation of 'session'

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +mcc.session_fail=Konnte Session nicht überprüfen.
```suggestion
mcc.session_fail=Konnte Sitzung nicht überprüfen.
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +mcc.session_fail=Konnte Session nicht überprüfen.
Fixing inconsistent translation of 'session'

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +mcc.server_protocol=§8Server Version : {0} (protocol v{1})
```suggestion
mcc.server_protocol=§8Server-Version : {0} (protocol v{1})
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +mcc.server_protocol=§8Server Version : {0} (protocol v{1})
https://context.reverso.net/%C3%BCbersetzung/englisch-deutsch/the+server+version

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +error.determine=Konnte Server Version nicht bestimmen.
```suggestion
error.determine=Konnte Server-Version nicht bestimmen.
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +error.determine=Konnte Server Version nicht bestimmen.
https://context.reverso.net/%C3%BCbersetzung/englisch-deutsch/the+server+version

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +error.forgeforce=Der zwanghafte Forge Support wird für diese Minecraft Version nicht unterstützt!
```suggestion
error.forgeforce=Der zwangshafte Forge-Support wird für diese Minecraft-Version nicht unterstützt!
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +error.forgeforce=Der zwanghafte Forge Support wird für diese Minecraft Version nicht unterstützt!
https://minecraft.fandom.com/de/wiki/Versionen

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +error.login.server=Login Server nicht erreichbar. Bitte versuche es später erneut.
```suggestion
error.login.server=Login-Server nicht erreichbar. Bitte versuche es später erneut.
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +error.login.server=Login Server nicht erreichbar. Bitte versuche es später erneut.
https://www.rz.uni-freiburg.de/services/serverdienste/loginserver

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +error.login.blocked=Falsches Passwort, gesperrte IP oder zu viele Login Versuche.
```suggestion
error.login.blocked=Falsches Passwort, gesperrte IP oder zu viele Logins.
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +error.login.blocked=Falsches Passwort, gesperrte IP oder zu viele Login Versuche.
More direct translation

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +error.login.premium=Dies ist kein premium Benutzer.
```suggestion
error.login.premium=Dies ist kein Premium-Benutzer.
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +error.login.premium=Dies ist kein premium Benutzer.
https://translate.google.com/?hl=de&sl=en&tl=de&text=premium%20user&op=translate

Even though it's Google Translate, it's accurate here.

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +error.login.ssl=SSL Fehler.
```suggestion
error.login.ssl=SSL-Fehler.
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +error.login.ssl=SSL Fehler.
https://praxistipps.chip.de/ssl-verbindungsfehler-beheben-so-gehts_32795

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +error.login.ssl_help=§8Anscheinend hast du dieses Programm mit MONO gestartet.\nBeim ersten Mal, musst du HTTPS Zertifikate mit folgendem Befehl importieren:\nmozroots --import --ask-remove
```suggestion
error.login.ssl_help=§8Anscheinend hast du dieses Programm mit MONO gestartet.\nBeim ersten Mal musst du HTTPS-Zertifikate mit folgendem Befehl importieren:\nmozroots --import --ask-remove
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +error.login.ssl_help=§8Anscheinend hast du dieses Programm mit MONO gestartet.\nBeim ersten Mal, musst du HTTPS Zertifikate mit folgendem Befehl importieren:\nmozroots --import --ask-remove
https://www.websecurity.digicert.com/de/de/security-topics/what-is-ssl-tls-https

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +error.timeout=Connection Timeout.
```suggestion
error.timeout=Verbindungs-Timeout.
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +error.timeout=Connection Timeout.
https://www.linguee.de/englisch-deutsch/uebersetzung/connection+timeout.html

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +error.unexpect_response=§8Unerwartete Antwort des Servers. (Ist das ein Minecraft Server?)
```suggestion
error.unexpect_response=§8Unerwartete Antwort des Servers. (Ist das ein Minecraft-Server?)
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +error.version_different=§8Der Server meldet eine andere Version, als manuell angegeben. Login könnte fehlschlagen.
```suggestion
error.version_different=§8Der Server meldet eine andere Version als manuell angegeben. Login könnte fehlschlagen.
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +error.no_version_report=§8Server gibt keine Protokoll Version an, autodetection wird nicht funktionieren.
```suggestion
error.no_version_report=§8Server gibt keine Protokoll-Version an, Autodetection wird nicht funktionieren.
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +error.auth=§8Es gab einen Fehlercode vom Server während die Authentication erneuert wurde: {0}
```suggestion
error.auth=§8Es gab einen Fehlercode vom Server, während die Authentication erneuert wurde: {0}
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +icmd.list=help <cmdname>. Verfügbare Befehle: {0}. Um die Hilfeseite des Servers zu bekommen schreibe '{1}send /help'.
```suggestion
icmd.list=help <cmdname>. Verfügbare Befehle: {0}. Für die Hilfeseite des Servers schreibe '{1}send /help'.
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +exception.palette.block=Bitte update das Block Types handling für diese Minecraft version. Siehe Materials.cs
```suggestion
exception.palette.block=Bitte update das Block Types Handling für diese Minecraft-Version. Siehe Materials.cs
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +exception.palette.entity=Bitte update das Entity Types handling für diese Minecraft version. Siehe EntityType.cs
```suggestion
exception.palette.entity=Bitte update das Entity Types Handling für diese Minecraft-Version. Siehe EntityType.cs
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +exception.palette.item=Bitte update das Item Types handling für diese Minecraft version. Siehe ItemType.cs
```suggestion
exception.palette.item=Bitte update das Item Types Handling für diese Minecraft-Version. Siehe ItemType.cs
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +exception.palette.packet=Bitte update die Packet Type Palette für diese Minecraft version. Siehe PacketTypePalette.cs
```suggestion
exception.palette.packet=Bitte update die Packet Type Palette für diese Minecraft-Version. Siehe PacketTypePalette.cs
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +exception.version_unsupport=Die Protokoll Version Nr.{0} wird nicht unterstützt.
```suggestion
exception.version_unsupport=Die Protokoll-Version Nr.{0} wird nicht unterstützt.
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +exception.palette.packet=Bitte update die Packet Type Palette für diese Minecraft version. Siehe PacketTypePalette.cs
https://minecraft.fandom.com/de/wiki/Versionen

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +exception.palette.item=Bitte update das Item Types handling für diese Minecraft version. Siehe ItemType.cs
https://minecraft.fandom.com/de/wiki/Versionen

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +exception.palette.entity=Bitte update das Entity Types handling für diese Minecraft version. Siehe EntityType.cs
https://minecraft.fandom.com/de/wiki/Versionen

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +exception.palette.block=Bitte update das Block Types handling für diese Minecraft version. Siehe Materials.cs
https://minecraft.fandom.com/de/wiki/Versionen

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +extra.inventory_disabled=§cInventar Interaktion wird in dieser Minecraft Version nicht unterstützt.
```suggestion
extra.inventory_disabled=§cInventar Interaktion wird in dieser Minecraft-Version nicht unterstützt.
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +extra.inventory_disabled=§cInventar Interaktion wird in dieser Minecraft Version nicht unterstützt.
https://minecraft.fandom.com/de/wiki/Versionen

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +extra.inventory_interact=Schreibe /inventory um mit deinem Inventar zu interagieren.
```suggestion
extra.inventory_interact=Schreibe /inventory, um mit deinem Inventar zu interagieren.
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +extra.entity_disabled=§cEntities werden für diese Minecraft Version nicht unterstützt.
```suggestion
extra.entity_disabled=§cEntities werden für diese Minecraft-Version nicht unterstützt.
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +extra.entity_disabled=§cEntities werden für diese Minecraft Version nicht unterstützt.
https://minecraft.fandom.com/de/wiki/Versionen

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +forge.version=§8Forge Protokoll Version : {0}
```suggestion
forge.version=§8Forge-Protokoll-Version : {0}
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +forge.send_mod=§8Sende verfälschte Mod Liste zum Server...
```suggestion
forge.send_mod=§8Sende verfälschte Mod-Liste zum Server...
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +forge.accept=§8Akzeptiere Mod Liste des Servers...
```suggestion
forge.accept=§8Akzeptiere Mod-Liste des Servers...
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +forge.complete=Forge Server Verbindung erfolgreich!
```suggestion
forge.complete=Forge-Server-Verbindung erfolgreich!
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +forge.with_mod=§8Server läuft mit {0} Forge mods.
```suggestion
forge.with_mod=§8Server läuft mit {0} Forge Mods.
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +forge.no_mod=§8Server läuft auf Forge ohne Modifikationen.
```suggestion
forge.no_mod=§8Server läuft auf Forge ohne Mods.
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +forge.no_mod=§8Server läuft auf Forge ohne Modifikationen.
Fixing inconsistent translation of 'mods'

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +forge.mod_list=§8Mod Liste:
```suggestion
forge.mod_list=§8Mod-Liste:
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +forge.fml2.mod=§8Empfange FML2 Server Mod Liste...
```suggestion
forge.fml2.mod=§8Empfange FML2 Server Mod-Liste...
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +forge.fml2.mod_send=§8Sende FML2 Client Mod List zurück
```suggestion
forge.fml2.mod_send=§8Sende FML2 Client Mod-Liste zurück
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +cache.loading=§8Lade Minecraft Profile: {0}
```suggestion
cache.loading=§8Lade Minecraft-Profile: {0}
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +cmd.entityCmd.customname=Custom Name
```suggestion
cmd.entityCmd.customname=Benutzerdefinierter Name
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +cmd.entityCmd.mainhand=Main Hand
```suggestion
cmd.entityCmd.mainhand=Haupthand
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +cmd.entityCmd.mainhand=Main Hand
https://translate.google.com/?hl=de&sl=en&tl=de&text=main%20hand&op=translate

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +cmd.entityCmd.offhane=Off Hand
```suggestion
cmd.entityCmd.offhane=Begleithand
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +cmd.entityCmd.chestplate=Chestplate
```suggestion
cmd.entityCmd.chestplate=Brustplatte
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +cmd.entityCmd.boots=Boots
```suggestion
cmd.entityCmd.boots=Schuhe
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +cmd.entityCmd.leggings=Leggings
```suggestion
cmd.entityCmd.leggings=Beinschutz
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +cmd.inventory.creative_fail=Item Vergabe durch den Creative Modus wurde abgelehnt.
```suggestion
cmd.inventory.creative_fail=Item-Vergabe durch den Creative Modus wurde abgelehnt.
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +cmd.inventory.desc=Inventar Befehl
```suggestion
cmd.inventory.desc=Inventar-Befehl
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +cmd.inventory.need_creative=Du musst im Creative Mudus sein!
```suggestion
cmd.inventory.need_creative=Du musst im Kreativmodus sein!
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +cmd.inventory.need_creative=Du musst im Creative Mudus sein!
https://minecraft.fandom.com/de/wiki/Kreativmodus

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +cmd.respawn.desc=Benutze dies um nach deinem Tod zu respawnen.
```suggestion
cmd.respawn.desc=Benutze dies, um nach deinem Tod zu respawnen.
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +cmd.script.desc=Lasse eine Skript Datei laufen.
```suggestion
cmd.script.desc=Lasse eine Skript-Datei laufen.
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +bot.autoCraft.cmd=Auto-crafting ChatBot Befehl
```suggestion
bot.autoCraft.cmd=Auto-Crafting ChatBot-Befehl
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +bot.autoCraft.alias=Auto-crafting ChatBot Befehl Alias
```suggestion
bot.autoCraft.alias=Auto-Crafting ChatBot-Befehl Alias
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +bot.autoCraft.recipe_not_exist=Der angegebene Rezeptname existiert nicht. Überprüfe deine Config Datei.
```suggestion
bot.autoCraft.recipe_not_exist=Der angegebene Rezeptname existiert nicht. Überprüfe deine Config-Datei.
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +bot.autoCraft.help.load=Lade Config Datei.
```suggestion
bot.autoCraft.help.load=Lade Config-Datei.
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +bot.autoCraft.help.reload=Lade Config Datei neu.
```suggestion
bot.autoCraft.help.reload=Lade Config-Datei neu.
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +bot.autoCraft.help.resetcfg=Schreibe die normale Beispiel Config in den Standard Pfad.
```suggestion
bot.autoCraft.help.resetcfg=Schreibe die normale Beispiel-Config in den Standardpfad.
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +bot.autoCraft.help.stop=Stoppe den aktuell laufenden crafting Prozess
```suggestion
bot.autoCraft.help.stop=Stoppe den aktuell laufenden Crafting-Prozess
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +bot.autoCraft.debug.no_config=Keine Config Datei gefunden. Schreibe eine neue...
```suggestion
bot.autoCraft.debug.no_config=Keine Config-Datei gefunden. Schreibe eine neue...
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +bot.autoCraft.exception.slot=Ungültiges Slot Feld im Rezept: {0}
```suggestion
bot.autoCraft.exception.slot=Ungültiges Slot-Feld im Rezept: {0}
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +bot.mailer.create.ignore=Erstelle neue Ignore Liste: {0}
```suggestion
bot.mailer.create.ignore=Erstelle neue Ignore-Liste: {0}
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +bot.mailer.load.db=Lade Datenbank Datei: {0}
```suggestion
bot.mailer.load.db=Lade Datenbank-Datei: {0}
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +bot.mailer.load.ignore=Lade Ignore Liste:
```suggestion
bot.mailer.load.ignore=Lade Ignore-Liste: 
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +bot.mailer.cmd.ignore.added=Füge {0} zur Ignore Liste hinzu!
```suggestion
bot.mailer.cmd.ignore.added=Füge {0} zur Ignore-Liste hinzu!
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +bot.mailer.cmd=mailer Befehl
```suggestion
bot.mailer.cmd=Mailer-Befehl
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +bot.replayCapture.created=Replay Datei erstellt.
```suggestion
bot.replayCapture.created=Replay-Datei erstellt.
```

2021-04-07 08:54 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +bot.scriptScheduler.loaded_task=Lade aufgabe:\n{0}
```suggestion
bot.scriptScheduler.loaded_task=Lade Aufgabe:\n{0}
```

2021-04-08 19:04 UTC, ORelio commented
Thanks @cyb3rko for reviewing the PR. Let me know @Daenges if you are done making changes.

2021-04-08 19:29 UTC, Daenges commented
@ORelio We both read through the translation and talked about it. We agreed on all accepted changes. Therefore, we have finished working on it.

2021-04-09 19:29 UTC, merged