Update de.ini
ORelio/Minecraft-Console-Client pull request #1539
Opened 2021-04-12 11:56 UTC by ReinforceZwei

@ORelio Do we merge it directly into the repo or ask for translator to help translating before merging?

2021-04-13 18:15 UTC, Daenges reviewed
I tried to translate everything.

2021-04-13 18:15 UTC, Daenges commented on MinecraftClient/Resources/lang/de.ini
> +mcc.realms_available=You have access to the following Realms worlds
```suggestion
mcc.realms_available=Du hast Zugang zu den folgenden Realms Welten
```

2021-04-13 18:15 UTC, Daenges commented on MinecraftClient/Resources/lang/de.ini
> +mcc.realms_join=Use realms:index as server IP to join the Realms world
```suggestion
mcc.realms_join=Nutze realms:index als Server IP um der Realms Welt beizutreten
```

2021-04-13 18:15 UTC, Daenges commented on MinecraftClient/Resources/lang/de.ini
> +error.realms.access_denied=This Realms world does not exist or access was denied
```suggestion
error.realms.access_denied=Diese Realms Welt exsistiert nicht oder der Zugang wurde verweigert
```

2021-04-13 18:15 UTC, Daenges commented on MinecraftClient/Resources/lang/de.ini
> +error.realms.server_unavailable=Realms server may require some time to start up. Please retry again later.
```suggestion
error.realms.server_unavailable=Der Realms Server braucht ein wenig Zeit zum starten. Bitte versuche es später erneut.
```

2021-04-13 18:15 UTC, Daenges commented on MinecraftClient/Resources/lang/de.ini
> +error.realms.disabled=Trying to join a Realms world but Realms support is disabled in config
```suggestion
error.realms.disabled=Versuche der Realms Welt beizutreten, allerdings wurde der Realms Support in der Config deaktiviert
```

2021-04-13 20:39 UTC, ORelio commented
Thanks @ReinforceZwei and @Daenges! Maybe @cyb3rko could have a look as in #1526?

2021-04-14 05:27 UTC, cyb3rko requested changes
Fixes some smaller issues

2021-04-14 05:27 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +mcc.realms_available=Du hast Zugang zu den folgenden Realms Welten
```suggestion
mcc.realms_available=Du hast Zugang zu den folgenden Realms-Welten
```

2021-04-14 05:27 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +mcc.realms_available=Du hast Zugang zu den folgenden Realms Welten
https://www.minecraft.net/de-de/realms/faq/ in the last paragraph

2021-04-14 05:27 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +mcc.realms_join=Nutze realms:index als Server IP um der Realms Welt beizutreten
```suggestion
mcc.realms_join=Nutze realms:index als Server-IP, um der Realms-Welt beizutreten
```

2021-04-14 05:27 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +error.realms.ip_error=Konnte die Server IP deiner Realms Welt nicht abfragen
```suggestion
error.realms.ip_error=Konnte die Server-IP deiner Realms-Welt nicht abfragen
```

2021-04-14 05:27 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +error.realms.access_denied=Diese Realms Welt exsistiert nicht oder der Zugang wurde verweigert
```suggestion
error.realms.access_denied=Diese Realms-Welt existiert nicht oder der Zugang wurde verweigert
```

2021-04-14 05:27 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +error.realms.server_unavailable=Der Realms Server braucht ein wenig Zeit zum starten. Bitte versuche es später erneut.
```suggestion
error.realms.server_unavailable=Der Realms-Server braucht ein wenig Zeit zum starten. Bitte versuche es später erneut.
```

2021-04-14 05:27 UTC, cyb3rko commented on MinecraftClient/Resources/lang/de.ini
> +error.realms.disabled=Versuche der Realms Welt beizutreten, allerdings wurde der Realms Support in der Config deaktiviert
```suggestion
error.realms.disabled=Versuche der Realms-Welt beizutreten, allerdings wurde der Realms-Support in der Config deaktiviert
```

2021-04-14 18:29 UTC, ORelio commented
Thanks @ReinforceZwei, @Daenges and @cyb3rko! Is it ready to merge?

2021-04-15 14:31 UTC, ReinforceZwei commented
@cyb3rko reacted with thumbs up. I guess it is ready for merging.

2021-04-15 14:32 UTC, merged